import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Copy, ExternalLink, Gift, Globe2, ShieldAlert, Users } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, YAxis } from "recharts";
import { toast } from "sonner";
import { api } from "../api";
import { useRuntime, useWallet } from "../context";
import { DEMO } from "../fixtures";
import type { Launch, Trade } from "../types";
import { Metric, TokenMark } from "../components/TokenCard";

const compact = new Intl.NumberFormat("en",{notation:"compact",maximumFractionDigits:2});
const money = new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:4});

export function Token() {
  const {id=""}=useParams(); const wallet=useWallet(); const {config}=useRuntime();
  const previewLaunch = DEMO.find(x=>x.id===id)??null;
  const [launch,setLaunch]=useState<Launch|null>(previewLaunch); const [trades,setTrades]=useState<Trade[]>([]); const [sample,setSample]=useState(Boolean(previewLaunch)); const [loaded,setLoaded]=useState(false);
  const [side,setSide]=useState<"buy"|"sell">("buy"); const [amount,setAmount]=useState("1");
  useEffect(()=>{api.launch(id).then(data=>{setLaunch(data.launch);setTrades(data.trades);setSample(false);}).catch(()=>undefined).finally(()=>setLoaded(true));},[id]);
  const n=Math.max(0,Number(amount)||0);
  const chart=useMemo(()=>!launch?[]:Array.from({length:38},(_,i)=>({i,p:Math.max(.000001,launch.priceUsd||.0001)*(.42+i/61)*(1+Math.sin(i*.67)*.05)})),[launch]);
  if(!launch && loaded)return <main className="page empty-state"><h2>Market not found</h2><p>This market is not present in the connected AQUA index.</p><Link className="primary" to="/">Return to Explore</Link></main>;
  if(!launch)return <main className="page"><div className="page-loading">Loading market…</div></main>;
  const fee=side==="buy"?n*config.fees.platformBps/10_000:null; const reward=side==="buy"&&launch.stockSymbol?n*config.fees.rewardsBps/10_000:null;
  const canTrade = !sample && config.transactionsEnabled;
  const activityRows = sample ? sampleTrades(launch) : trades;
  const explorerUrl = `https://explorer.solana.com/address/${launch.mint}${config.network === "devnet" ? "?cluster=devnet" : ""}`;

  return <main className="page token-page">
    <Link className="back" to="/"><ArrowLeft/>Explore markets</Link>
    {sample&&<div className="sample-banner"><b>SAMPLE MARKET</b><span>All prices, holders, trades and rewards on this page are illustrative.</span></div>}
    <section className="token-hero"><div className="token-identity"><TokenMark launch={launch} large/><div><div><h1>{launch.name}</h1><span>${launch.symbol}</span><em className={launch.status}>{launch.status==="orca"?"WHIRLPOOL":"WAVEBREAK"}</em></div><p>{launch.description}</p><footer>{launch.xUrl&&<a href={launch.xUrl} target="_blank" rel="noreferrer">X <ExternalLink/></a>}{launch.websiteUrl&&<a href={launch.websiteUrl} target="_blank" rel="noreferrer"><Globe2/> Website</a>}{!sample&&<a href={explorerUrl} target="_blank" rel="noreferrer">Explorer <ExternalLink/></a>}<button onClick={()=>{void navigator.clipboard.writeText(launch.mint);toast.success("Mint copied");}}><Copy/> {launch.mint.slice(0,5)}…{launch.mint.slice(-4)}</button></footer></div></div><div className="hero-metrics"><Metric label={launch.stockSymbol?"Stock reward":"Reward route"} value={launch.stockSymbol??"Off"}/><Metric label="Reward vault" value={launch.stockSymbol?`${launch.rewardVaultStock.toFixed(2)} ${launch.stockSymbol}`:"None"}/><Metric label="Holders" value={compact.format(launch.holderCount)}/><Metric label="Market cap" value={`$${compact.format(launch.marketCapUsd)}`}/></div></section>
    <div className="token-layout"><section className="token-main">
      <div className="chart-panel"><header><div><small>ORCA WAVEBREAK PRICE</small><b>{money.format(launch.priceUsd)}</b></div><span>{sample?"ILLUSTRATIVE":"INDEXED"}</span></header><div className="chart"><ResponsiveContainer><AreaChart data={chart}><defs><linearGradient id="tokenFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#73edf2" stopOpacity=".25"/><stop offset="1" stopColor="#73edf2" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} stroke="rgba(137,214,223,.07)"/><YAxis orientation="right" axisLine={false} tickLine={false} tick={{fill:"#648087",fontSize:10}}/><Tooltip contentStyle={{background:"#061820",border:"1px solid rgba(137,214,223,.18)",borderRadius:8}}/><Area type="monotone" dataKey="p" stroke="#73edf2" fill="url(#tokenFill)" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></div>
      <div className="info-grid"><div className="info-panel reward"><Gift/><b>{launch.stockSymbol?`Earn ${launch.stockSymbol}`:"No stock reward"}</b>{launch.stockSymbol?<><div><Metric label="Distributed" value={`$${compact.format(launch.rewardDistributedUsd)}`}/><Metric label="In vault" value={`${launch.rewardVaultStock.toFixed(3)} ${launch.stockSymbol}`}/></div><p>One percent of trading activity funds batched stock purchases. Eligible shares are designed to use balance and holding time.</p></>:<p>This market does not collect a tokenized stock reward fee.</p>}</div><div className="info-panel"><small>{launch.status === "orca" ? "ORCA WHIRLPOOL" : "WAVEBREAK BONDING"}</small><h2>{launch.status === "orca" ? "Live" : `${launch.progress.toFixed(1)}%`}</h2>{launch.status !== "orca" && <div className="progress big"><i style={{width:`${launch.progress}%`}}/></div>}<p>{launch.status === "orca" ? "Bonding is complete and this market now trades in an Orca Whirlpool." : `${launch.realSolReserve.toFixed(2)} of ${config.graduationSol} SOL before graduation into an Orca Whirlpool.`}</p></div></div>
      <div className="activity"><header><div><b>Market activity</b><span>{sample?"Illustrative transactions":"Indexed transactions"}</span></div><strong>{launch.txCount.toLocaleString()} total</strong></header><div className="activity-scroll"><table><thead><tr><th>Type</th><th>Wallet</th><th>SOL</th><th>Tokens</th></tr></thead><tbody>{activityRows.length?activityRows.map(t=><tr key={t.id}><td className={t.side}>{t.side.toUpperCase()}</td><td>{t.wallet}</td><td>{t.solAmount.toFixed(3)}</td><td>{compact.format(t.tokenAmount)}</td></tr>):<tr><td colSpan={4} className="no-activity">No indexed trades yet.</td></tr>}</tbody></table></div></div>
    </section><aside className="trade-card"><div className="trade-tabs"><button className={side==="buy"?"active":""} onClick={()=>setSide("buy")}>Buy</button><button className={side==="sell"?"active":""} onClick={()=>setSide("sell")}>Sell</button></div><label>You pay</label><div className="trade-input"><input value={amount} inputMode="decimal" onChange={e=>setAmount(e.target.value.replace(/[^0-9.]/g,""))}/><b>{side==="buy"?"SOL":launch.symbol}</b></div><TradeRow label="Estimated receive" value="Quoted by Orca" strong/><TradeRow label="Platform fee" value={fee===null?"Applied to Orca quote":`${fee.toFixed(4)} SOL`}/><TradeRow label="Stock reward stream" value={!launch.stockSymbol?"Off":reward===null?"Applied to Orca quote":`${reward.toFixed(4)} SOL`} accent={Boolean(launch.stockSymbol)}/><TradeRow label="Reward asset" value={launch.stockSymbol??"None"}/><button className="primary full" disabled={!n||!canTrade} onClick={()=>{if(!wallet.address)wallet.setModalOpen(true);}}>{sample?"Preview only":!config.transactionsEnabled?"Trading unavailable":wallet.address?(side==="buy"?`Buy ${launch.symbol}`:`Sell ${launch.symbol}`):"Connect wallet"}</button>{!canTrade&&<div className="locked"><ShieldAlert/><span><b>{sample?"Sample market":"Transactions disabled"}</b>{sample?"No transaction can be submitted from example data.":"Orca Wavebreak integration must be configured before trading."}</span></div>}<div className="creator"><span>Creator</span><b>{launch.creatorWallet}</b><span>Developer buy</span><b>{launch.devBuySol.toFixed(1)} SOL · {launch.devSupplyPct.toFixed(1)}%</b><span>Holders</span><b><Users/> {compact.format(launch.holderCount)}</b></div></aside></div>
  </main>;
}

function TradeRow({label,value,strong,accent}:{label:string;value:string;strong?:boolean;accent?:boolean}) { return <div className={`trade-row ${strong?"strong":""}`}><span>{label}</span><b className={accent?"green":""}>{value}</b></div>; }
function sampleTrades(l:Launch):Trade[] { return Array.from({length:6},(_,i)=>({id:`${l.id}-${i}`,wallet:`${["7mQx","K8p2","3Zva","P9eL","6Twu","A1cx"][i]}…${["fQ2","9Mp","k71","w30","Jq4","8xd"][i]}`,side:i===2||i===5?"sell":"buy",solAmount:.17+((i*37)%20)/10,tokenAmount:82900+i*182300,priceUsd:l.priceUsd,createdAt:Date.now()-i*90000})); }
