import { useState } from "react";
import { RotateCcw, SlidersHorizontal, X } from "lucide-react";
import { Select } from "./Select";
import { useDialog } from "./useDialog";
export const marketFilterKeys=["pair","mode","dex","minCap","maxCap","minVolume","minLiquidity","minHolders","ageHours"] as const;
export type MarketFilterValues=Record<(typeof marketFilterKeys)[number],string>;
export function readMarketFilters(params:URLSearchParams):MarketFilterValues{return Object.fromEntries(marketFilterKeys.map(key=>[key,params.get(key)??(["pair","mode","dex"].includes(key)?"all":"")])) as MarketFilterValues;}
export function MarketFilters({initial,pairs,onApply,onClose}:{initial:MarketFilterValues;pairs:string[];onApply:(values:MarketFilterValues)=>void;onClose:()=>void}){
 const [draft,setDraft]=useState(initial),[error,setError]=useState("");const ref=useDialog<HTMLElement>(true,onClose);
 const change=(key:keyof MarketFilterValues,value:string)=>{setDraft(old=>({...old,[key]:value}));setError("");};
 function apply(){for(const key of ["minCap","maxCap","minVolume","minLiquidity","minHolders"] as const){if(draft[key]&&(!Number.isFinite(Number(draft[key]))||Number(draft[key])<0||Number(draft[key])>1e15)){setError("Enter a valid positive amount.");return;}}if(draft.minCap&&draft.maxCap&&Number(draft.minCap)>Number(draft.maxCap)){setError("Maximum market cap must be greater than the minimum.");return;}if(draft.minHolders&&!Number.isInteger(Number(draft.minHolders))){setError("Enter a whole number of holders.");return;}onApply(draft);}
 return <div className="wallet-overlay market-filter-overlay" onMouseDown={onClose}><section ref={ref} className="market-filter-modal" role="dialog" aria-modal="true" aria-labelledby="market-filter-title" onMouseDown={event=>event.stopPropagation()}>
  <header><span className="filter-modal-icon"><SlidersHorizontal size={20}/></span><h2 id="market-filter-title">Filter markets</h2><button type="button" className="modal-close" aria-label="Close filters" onClick={onClose}><X size={19}/></button></header>
  <form onSubmit={event=>{event.preventDefault();apply();}}><div className="market-filter-body">
   <div className="filter-form-grid"><label>Pair<Select aria-label="Pair" value={draft.pair} onChange={event=>change("pair",event.target.value)}><option value="all">All pairs</option>{pairs.map(pair=><option key={pair}>{pair}</option>)}<option value="STOCK">All xStocks</option></Select></label><label>Rewards<Select aria-label="Rewards" value={draft.mode} onChange={event=>change("mode",event.target.value)}><option value="all">All reward modes</option><option value="holder_rewards">Holder rewards</option><option value="buyback_burn">Buyback & burn</option><option value="jackpot">Jackpot</option></Select></label></div>
   <fieldset className="filter-dex"><legend>DEX profile</legend><div>{[["all","Any"],["paid","Paid"],["unpaid","Not paid"]].map(([value,label])=><button type="button" key={value} aria-pressed={draft.dex===value} onClick={()=>change("dex",value)}>{label}</button>)}</div></fieldset>
   <fieldset className="filter-cap"><legend>Market cap</legend><div className="filter-form-grid"><label><span className="sr-only">Minimum market cap</span><div className="filter-number"><span>$</span><input aria-label="Minimum market cap" inputMode="decimal" placeholder="Min" value={draft.minCap} onChange={event=>change("minCap",event.target.value)}/></div></label><label><span className="sr-only">Maximum market cap</span><div className="filter-number"><span>$</span><input aria-label="Maximum market cap" inputMode="decimal" placeholder="Max" value={draft.maxCap} onChange={event=>change("maxCap",event.target.value)}/></div></label></div></fieldset>
   <div className="filter-form-grid"><label>24h volume, min<div className="filter-number"><span>$</span><input aria-label="Minimum 24h volume" inputMode="decimal" placeholder="Any" value={draft.minVolume} onChange={event=>change("minVolume",event.target.value)}/></div></label><label>Liquidity, min<div className="filter-number"><span>$</span><input aria-label="Minimum liquidity" inputMode="decimal" placeholder="Any" value={draft.minLiquidity} onChange={event=>change("minLiquidity",event.target.value)}/></div></label><label>Holders, min<input aria-label="Minimum holders" inputMode="numeric" placeholder="Any" value={draft.minHolders} onChange={event=>change("minHolders",event.target.value)}/></label><label>Launched<Select aria-label="Launched" value={draft.ageHours} onChange={event=>change("ageHours",event.target.value)}><option value="">Any time</option><option value="1">Last hour</option><option value="24">Last 24 hours</option><option value="168">Last 7 days</option><option value="720">Last 30 days</option></Select></label></div>
  </div>{error&&<p className="filter-error" role="alert">{error}</p>}<footer><button type="button" className="filter-reset" onClick={()=>{setDraft(readMarketFilters(new URLSearchParams()));setError("");}}><RotateCcw size={15}/>Reset</button><button type="submit" className="primary">Apply filters</button></footer></form>
 </section></div>;
}
