import { useState } from "react";
import { StudioSitePreview } from "./StudioSitePreview";
import type { StudioFile } from "../studio-api";
const demos:Record<string,string>={
  "Token website":'<main><nav><a href="index.html">Home</a> · <a href="lore.html">Our story</a></nav><h1>A home for your community.</h1><p>Your artwork, story and token links in one fast website.</p><a href="lore.html">Read the story →</a></main>',
  "Mini-game":'<main><h1>Catch a bubble</h1><p>Score: <output id="score">0</output></p><button id="catch">Pop</button></main><script>let score=0;document.getElementById("catch").onclick=function(){document.getElementById("score").textContent=String(++score);this.style.transform="translateX("+((score%4)*30)+"px)";};</script>',
  "Meme generator":'<main><h1>Make it yours.</h1><label>Your caption <input id="caption" maxlength="100" placeholder="A very serious community"/></label><button id="make">Make meme</button><figure style="font-size:2rem" id="meme">🐋<figcaption id="result">Your caption goes here</figcaption></figure><button id="download">Download SVG</button></main><script>document.getElementById("make").onclick=()=>document.getElementById("result").textContent=document.getElementById("caption").value||"A very serious community";document.getElementById("download").onclick=()=>{const text=document.getElementById("result").textContent.replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",\'"\':"&quot;"}[c]));const url=URL.createObjectURL(new Blob([\'<svg xmlns="http://www.w3.org/2000/svg" width="800" height="500"><rect width="800" height="500" fill="#d7f1fb"/><text x="400" y="200" text-anchor="middle" font-size="100">🐋</text><text x="400" y="350" text-anchor="middle" font-size="26">\'+text+\'</text></svg>\'],{type:"image/svg+xml"}));const a=document.createElement("a");a.href=url;a.download="meme.svg";a.click();URL.revokeObjectURL(url);};</script>',
};
const style='<style>body{margin:0;background:#e8f4fa;color:#163a4e;font:16px/1.6 system-ui}main{padding:32px;max-width:650px;margin:auto}h1{font-size:32px;line-height:1.1}button{background:#0875bd;color:white;border:0;border-radius:8px;padding:12px 18px;cursor:pointer}input{display:block;padding:12px;margin:12px 0;width:85%}a{color:#006ca9}</style>';
export function StudioExamples(){
  const [selected,setSelected]=useState<string|null>(null);
  const files:StudioFile[]=selected?[{path:"frontend/index.html",content:style+demos[selected],encoding:"utf8",locked:false},{path:"frontend/lore.html",content:style+'<main><a href="index.html">← Home</a><h1>Every community starts somewhere.</h1><p>Turn an idea into a place people want to return to.</p></main>',encoding:"utf8",locked:false}]:[];
  return <section className="dashboard-section"><h2>Try a small example</h2><p>Working local demos, no wallet or AI credit needed. Preview downloads and external requests stay blocked.</p><div className="segmented">{Object.keys(demos).map(name=><button key={name} aria-pressed={selected===name} onClick={()=>setSelected(name)}>{name}</button>)}{selected&&<button onClick={()=>setSelected(null)}>Close example</button>}</div>{selected&&<div style={{height:400,marginTop:16}}><StudioSitePreview key={selected} files={files}/></div>}</section>;
}
