import { useEffect, useState } from "react";
import { API_URL } from "../api";
import { useWallet } from "../context";
type Candle={time:number;open:number;high:number;low:number;close:number;volume:number;ownBuys:number;ownSells:number};
export function TradeCandles({id,range,onRangeChange}:{id:string;range:string;onRangeChange:(value:string)=>void}){
  const {address}=useWallet(),[interval,setIntervalValue]=useState("5m"),[data,setData]=useState<{candles:Candle[];quoteSymbol:string;intervalSeconds:number;note:string}|null>(null),[error,setError]=useState(""),[count,setCount]=useState(80),[end,setEnd]=useState<number|null>(null),[selected,setSelected]=useState<Candle|null>(null);
  useEffect(()=>{const controller=new AbortController();setData(null);setError("");setEnd(null);
    let pending=false;
    const load=()=>{if(pending)return;pending=true;fetch(API_URL+"/api/launches/"+encodeURIComponent(id)+"/candles?"+new URLSearchParams({range,interval,...(address?{wallet:address}:{})}),{signal:controller.signal}).then(async r=>{if(!r.ok)throw Error("Trade candles unavailable");return r.json();}).then(value=>{if(!controller.signal.aborted){setData(value);setError("");}}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{pending=false;});};
    void load();const refresh=()=>{if(document.visibilityState==="visible")void load();};const timer=window.setInterval(refresh,15_000);window.addEventListener("focus",refresh);
    return()=>{controller.abort();window.clearInterval(timer);window.removeEventListener("focus",refresh);};
  },[id,range,interval,address]);
  const all=data?.candles??[],last=end??all.length,points=all.slice(Math.max(0,last-count),last);
  const high=Math.max(...points.map(p=>p.high)),low=Math.min(...points.map(p=>p.low)),spread=high-low||high*.01||1,maxVol=Math.max(...points.map(p=>p.volume),1);
  const y=(n:number)=>20+(high-n)/spread*220,step=700/Math.max(points.length,1);
  return <section><div className="market-toolbar"><label>History<select value={range} onChange={e=>onRangeChange(e.target.value)}>{["1h","24h","7d","all"].map(v=><option key={v}>{v}</option>)}</select></label><label>Candle interval<select value={interval} onChange={e=>setIntervalValue(e.target.value)}>{["1m","5m","1h","1d"].map(v=><option key={v}>{v}</option>)}</select></label><button className="soft-button" disabled={last<=count} onClick={()=>setEnd(Math.max(count,last-Math.floor(count/2)))}>← Earlier</button><button className="soft-button" disabled={last>=all.length} onClick={()=>setEnd(Math.min(all.length,last+Math.floor(count/2)))}>Later →</button><label>Zoom<input aria-label="Visible candles" type="range" min="20" max="160" value={count} onChange={e=>setCount(Number(e.target.value))}/></label></div>
    {error?<p role="alert">{error}</p>:!data?<p>Loading transaction-derived candles…</p>:!points.length?<p>No indexed trades in this range. No synthetic candles are shown.</p>:<><p className="status-inline">{selected?new Date(selected.time).toLocaleString()+": O "+selected.open.toPrecision(5)+" H "+selected.high.toPrecision(5)+" L "+selected.low.toPrecision(5)+" C "+selected.close.toPrecision(5):"Focus or hover a candle for OHLC values"} {data.quoteSymbol}</p><svg viewBox="0 0 800 320" role="img" aria-label={"Trade price candles and volume in "+data.quoteSymbol} style={{width:"100%",minHeight:230}}>{[0,1,2,3].map(i=><g key={i}><line x1="0" x2="705" y1={20+i*220/3} y2={20+i*220/3} stroke="var(--aqua-border)"/><text x="710" y={24+i*220/3} fontSize="11" fill="var(--aqua-muted)">{(high-i*spread/3).toPrecision(4)}</text></g>)}{points.map((p,i)=>{const x=i*step+step/2,color=p.close>=p.open?"#128666":"#cc4d57";return <g key={p.time} tabIndex={0} onFocus={()=>setSelected(p)} onMouseEnter={()=>setSelected(p)} aria-label={new Date(p.time).toLocaleString()+", close "+p.close+", volume "+p.volume}><title>{new Date(p.time).toLocaleString()} · Open {p.open} · High {p.high} · Low {p.low} · Close {p.close} · Volume {p.volume}</title><line x1={x} x2={x} y1={y(p.high)} y2={y(p.low)} stroke={color}/><rect x={x-step*.3} y={Math.min(y(p.open),y(p.close))} width={Math.max(1,step*.6)} height={Math.max(1,Math.abs(y(p.close)-y(p.open)))} fill={color}/><rect x={x-step*.3} y={300-p.volume/maxVol*40} width={Math.max(1,step*.6)} height={p.volume/maxVol*40} fill={color} opacity=".4"/>{p.ownBuys+p.ownSells>0&&<text x={x} y={y(p.low)+14} fontSize="10" textAnchor="middle" fill={color}>{p.ownBuys?"B":""}{p.ownSells?"S":""}</text>}</g>;})}<text x="0" y="318" fontSize="11" fill="var(--aqua-muted)">{new Date(points[0].time).toLocaleString()}</text><text x="700" y="318" fontSize="11" textAnchor="end" fill="var(--aqua-muted)">{new Date(points[points.length-1].time).toLocaleString()}</text></svg><p className="status-inline">{data.note} Interval: {data.intervalSeconds/60} minutes. B/S mark your indexed trades.</p></>}
  </section>;
}
