import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { Toaster } from "sonner";
import { App } from "./App";
import { RuntimeProvider, WalletProvider } from "./context";
import "./styles.css";
import "./polish.css";
import "./aqua-theme.css";
import "./developer.css";
import "./market.css";
import "./pages/studio.css";
createRoot(document.getElementById("root")!).render(<StrictMode><RuntimeProvider><WalletProvider><App/><Toaster theme="light" richColors/></WalletProvider></RuntimeProvider></StrictMode>);
